// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX1h2X7un9VdtS-AMs5SvbKTp695hx6TY',
    appId: '1:224889186136:web:30d6c46979fd42004f672d',
    messagingSenderId: '224889186136',
    projectId: 'siankes',
    authDomain: 'siankes.firebaseapp.com',
    storageBucket: 'siankes.firebasestorage.app',
    measurementId: 'G-ZLKYRHHRE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Q-_EcS38cgvC1ZWyBYG1GccQ1VjuSA0',
    appId: '1:224889186136:android:b8493da5149336e44f672d',
    messagingSenderId: '224889186136',
    projectId: 'siankes',
    storageBucket: 'siankes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDves3nrKOwoBuCGyuTctXUuq7aIStI0',
    appId: '1:224889186136:ios:e957f49665eb97aa4f672d',
    messagingSenderId: '224889186136',
    projectId: 'siankes',
    storageBucket: 'siankes.firebasestorage.app',
    iosBundleId: 'com.example.projek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASDves3nrKOwoBuCGyuTctXUuq7aIStI0',
    appId: '1:224889186136:ios:e957f49665eb97aa4f672d',
    messagingSenderId: '224889186136',
    projectId: 'siankes',
    storageBucket: 'siankes.firebasestorage.app',
    iosBundleId: 'com.example.projek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX1h2X7un9VdtS-AMs5SvbKTp695hx6TY',
    appId: '1:224889186136:web:901a428251465a934f672d',
    messagingSenderId: '224889186136',
    projectId: 'siankes',
    authDomain: 'siankes.firebaseapp.com',
    storageBucket: 'siankes.firebasestorage.app',
    measurementId: 'G-B1K5T7FNBT',
  );
}
